/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SegmentContainer {
        "backgroundColor": string;
        "segTitle": string;
    }
    interface TcBulletpointList {
        "backgroundColor": string;
        "bulletpoints": "[]";
        "header": string;
    }
    interface TcCollapsible {
        "backgroundColor": string;
        "colTitle": string;
        "description": string;
        "tags": string;
    }
    interface TcGridContainer {
        "backgroundColor": string;
        "columns": 1|2|3|4|5|6;
        "gap": 'sm' | 'md' | 'lg' | 'xl';
        "lgColumns": 1|2|3|4|5|6;
        "mdColumns": 1|2|3|4|5|6;
    }
    interface TcGridItem {
        "giTitle": string;
        "imageSrc": string;
        "link": string;
        "width": string;
    }
    interface TcImgQuoteCard {
        "altText": string;
        "backgroundColor": string;
        "borderColor": string;
        "imageOnLeft": boolean;
        "imageSrc": string;
        "pro": string;
        "quote": string;
        "quotee": string;
    }
    interface TcImgTextCard {
        "borderColor": string;
        "detailedDescription": string;
        "imageOnLeft": boolean;
        "imageSrc": string;
        "shortDescription": string;
        "tcImgTextCardTitle": string;
    }
    interface TcJobListing {
        "description": string;
        "imageSrc": string;
        "jobTitle": string;
        "tags": string;
    }
    interface TcOpenPositions {
        "level": string;
    }
    interface TcSvgIconCard {
        "advantageTitle": string;
        "backgroundColor": string;
        "iconBackground": string;
        "iconColor": string;
        "iconSvgPath": string;
        "iconSvgViewBox": string;
        "iconSvgXmlns": string;
        "text": string;
    }
}
declare global {
    interface HTMLSegmentContainerElement extends Components.SegmentContainer, HTMLStencilElement {
    }
    var HTMLSegmentContainerElement: {
        prototype: HTMLSegmentContainerElement;
        new (): HTMLSegmentContainerElement;
    };
    interface HTMLTcBulletpointListElement extends Components.TcBulletpointList, HTMLStencilElement {
    }
    var HTMLTcBulletpointListElement: {
        prototype: HTMLTcBulletpointListElement;
        new (): HTMLTcBulletpointListElement;
    };
    interface HTMLTcCollapsibleElement extends Components.TcCollapsible, HTMLStencilElement {
    }
    var HTMLTcCollapsibleElement: {
        prototype: HTMLTcCollapsibleElement;
        new (): HTMLTcCollapsibleElement;
    };
    interface HTMLTcGridContainerElement extends Components.TcGridContainer, HTMLStencilElement {
    }
    var HTMLTcGridContainerElement: {
        prototype: HTMLTcGridContainerElement;
        new (): HTMLTcGridContainerElement;
    };
    interface HTMLTcGridItemElement extends Components.TcGridItem, HTMLStencilElement {
    }
    var HTMLTcGridItemElement: {
        prototype: HTMLTcGridItemElement;
        new (): HTMLTcGridItemElement;
    };
    interface HTMLTcImgQuoteCardElement extends Components.TcImgQuoteCard, HTMLStencilElement {
    }
    var HTMLTcImgQuoteCardElement: {
        prototype: HTMLTcImgQuoteCardElement;
        new (): HTMLTcImgQuoteCardElement;
    };
    interface HTMLTcImgTextCardElement extends Components.TcImgTextCard, HTMLStencilElement {
    }
    var HTMLTcImgTextCardElement: {
        prototype: HTMLTcImgTextCardElement;
        new (): HTMLTcImgTextCardElement;
    };
    interface HTMLTcJobListingElement extends Components.TcJobListing, HTMLStencilElement {
    }
    var HTMLTcJobListingElement: {
        prototype: HTMLTcJobListingElement;
        new (): HTMLTcJobListingElement;
    };
    interface HTMLTcOpenPositionsElement extends Components.TcOpenPositions, HTMLStencilElement {
    }
    var HTMLTcOpenPositionsElement: {
        prototype: HTMLTcOpenPositionsElement;
        new (): HTMLTcOpenPositionsElement;
    };
    interface HTMLTcSvgIconCardElement extends Components.TcSvgIconCard, HTMLStencilElement {
    }
    var HTMLTcSvgIconCardElement: {
        prototype: HTMLTcSvgIconCardElement;
        new (): HTMLTcSvgIconCardElement;
    };
    interface HTMLElementTagNameMap {
        "segment-container": HTMLSegmentContainerElement;
        "tc-bulletpoint-list": HTMLTcBulletpointListElement;
        "tc-collapsible": HTMLTcCollapsibleElement;
        "tc-grid-container": HTMLTcGridContainerElement;
        "tc-grid-item": HTMLTcGridItemElement;
        "tc-img-quote-card": HTMLTcImgQuoteCardElement;
        "tc-img-text-card": HTMLTcImgTextCardElement;
        "tc-job-listing": HTMLTcJobListingElement;
        "tc-open-positions": HTMLTcOpenPositionsElement;
        "tc-svg-icon-card": HTMLTcSvgIconCardElement;
    }
}
declare namespace LocalJSX {
    interface SegmentContainer {
        "backgroundColor"?: string;
        "segTitle"?: string;
    }
    interface TcBulletpointList {
        "backgroundColor"?: string;
        "bulletpoints"?: "[]";
        "header"?: string;
    }
    interface TcCollapsible {
        "backgroundColor"?: string;
        "colTitle"?: string;
        "description"?: string;
        "tags"?: string;
    }
    interface TcGridContainer {
        "backgroundColor"?: string;
        "columns"?: 1|2|3|4|5|6;
        "gap"?: 'sm' | 'md' | 'lg' | 'xl';
        "lgColumns"?: 1|2|3|4|5|6;
        "mdColumns"?: 1|2|3|4|5|6;
    }
    interface TcGridItem {
        "giTitle"?: string;
        "imageSrc"?: string;
        "link"?: string;
        "width"?: string;
    }
    interface TcImgQuoteCard {
        "altText"?: string;
        "backgroundColor"?: string;
        "borderColor"?: string;
        "imageOnLeft"?: boolean;
        "imageSrc"?: string;
        "pro"?: string;
        "quote"?: string;
        "quotee"?: string;
    }
    interface TcImgTextCard {
        "borderColor"?: string;
        "detailedDescription"?: string;
        "imageOnLeft"?: boolean;
        "imageSrc"?: string;
        "shortDescription"?: string;
        "tcImgTextCardTitle"?: string;
    }
    interface TcJobListing {
        "description"?: string;
        "imageSrc"?: string;
        "jobTitle"?: string;
        "tags"?: string;
    }
    interface TcOpenPositions {
        "level"?: string;
    }
    interface TcSvgIconCard {
        "advantageTitle"?: string;
        "backgroundColor"?: string;
        "iconBackground"?: string;
        "iconColor"?: string;
        "iconSvgPath"?: string;
        "iconSvgViewBox"?: string;
        "iconSvgXmlns"?: string;
        "text"?: string;
    }
    interface IntrinsicElements {
        "segment-container": SegmentContainer;
        "tc-bulletpoint-list": TcBulletpointList;
        "tc-collapsible": TcCollapsible;
        "tc-grid-container": TcGridContainer;
        "tc-grid-item": TcGridItem;
        "tc-img-quote-card": TcImgQuoteCard;
        "tc-img-text-card": TcImgTextCard;
        "tc-job-listing": TcJobListing;
        "tc-open-positions": TcOpenPositions;
        "tc-svg-icon-card": TcSvgIconCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "segment-container": LocalJSX.SegmentContainer & JSXBase.HTMLAttributes<HTMLSegmentContainerElement>;
            "tc-bulletpoint-list": LocalJSX.TcBulletpointList & JSXBase.HTMLAttributes<HTMLTcBulletpointListElement>;
            "tc-collapsible": LocalJSX.TcCollapsible & JSXBase.HTMLAttributes<HTMLTcCollapsibleElement>;
            "tc-grid-container": LocalJSX.TcGridContainer & JSXBase.HTMLAttributes<HTMLTcGridContainerElement>;
            "tc-grid-item": LocalJSX.TcGridItem & JSXBase.HTMLAttributes<HTMLTcGridItemElement>;
            "tc-img-quote-card": LocalJSX.TcImgQuoteCard & JSXBase.HTMLAttributes<HTMLTcImgQuoteCardElement>;
            "tc-img-text-card": LocalJSX.TcImgTextCard & JSXBase.HTMLAttributes<HTMLTcImgTextCardElement>;
            "tc-job-listing": LocalJSX.TcJobListing & JSXBase.HTMLAttributes<HTMLTcJobListingElement>;
            "tc-open-positions": LocalJSX.TcOpenPositions & JSXBase.HTMLAttributes<HTMLTcOpenPositionsElement>;
            "tc-svg-icon-card": LocalJSX.TcSvgIconCard & JSXBase.HTMLAttributes<HTMLTcSvgIconCardElement>;
        }
    }
}
